name: Generate PDF

on:
  push:
    branches: [ main ]
    paths:
      - 'slide.md'
      - 'images/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Japanese fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-noto-cjk fonts-noto-cjk-extra
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install @marp-team/marp-cli
      run: npm install -g @marp-team/marp-cli
    
    - name: Generate PDF
      run: marp slide.md -o slide.pdf --pdf-notes --allow-local-files --html --pdf-notes --chrome-args='--font-render-hinting=none'
    
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: presentation-pdf
        path: slide.pdf 